### ISSUE TITLE
Update streaming section with AOE2 Companion

### ISSUE THREAD

**Issue by kmanan** [Arkanosis/awesome-aoe2#4]
Just a heads up, AoE2 Companion has API calls for streaming: https://aoe2companion.com/api-nightbot

!Match !rank etc. Not overlays afaik. One of the overlay devs has said that they'll update their overlay at some point soon.

**Comment by Arkanosis** [comment]
Thanks a lot for the heads up!

I was not really familiar with Nightbot until your comment, but I'll look into it and add it to the streaming tools section.

As for the public API, I'll probably add a dedicated section once it's available. It think some other websites also develop their API now that aoe2.net is unavailable. That will definitely be of interest to developers.

Thanks again!

**Comment by Arkanosis** [comment]
I just got up-to-date with Nightbot and it's actually much simpler than I thought, so I added your link right away.

Thanks a lot for the heads up! :)
